# Generated by Django 5.2.9 on 2025-12-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_diagnosis_invoice_payment_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invoice_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
