# Generated by Django 5.2.9 on 2025-12-27 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_invalid_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 2, 45, 41, 419488, tzinfo=datetime.timezone.utc)),
        ),
    ]
