# Generated by Django 5.2.9 on 2025-12-27 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 2, 46, 38, 18866, tzinfo=datetime.timezone.utc)),
        ),
    ]
