# Generated by Django 5.2.9 on 2025-12-27 15:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_refactor_treatment_service_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_record',
            field=models.OneToOneField(blank=True, help_text='Medical record for this appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_record', to='staff.medicalrecord'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, help_text='Nurse assisting in the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_appointments', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 16, 23, 5, 395697, tzinfo=datetime.timezone.utc)),
        ),
    ]
