# Generated by Django 5.2.9 on 2025-12-27 15:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_appointment_medical_record_appointment_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 16, 27, 52, 155609, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, db_column='nurse_id', help_text='Nurse assisting in the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_appointments', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='staff.staff'),
        ),
    ]
