# Generated by Django 5.2.9 on 2025-12-27 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_appointment_end_time_alter_appointment_nurse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 27, 16, 30, 20, 836743, tzinfo=datetime.timezone.utc)),
        ),
    ]
