# Generated by Django 5.2.9 on 2025-12-27 23:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='radiology_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 0, 4, 52, 862445, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, db_column='chief_complaint', null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='staff',
            field=models.ForeignKey(db_column='staff', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='staff.staff'),
        ),
    ]
