# Generated by Django 5.2.9 on 2025-12-27 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_appointment_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 0, 31, 1, 779836, tzinfo=datetime.timezone.utc)),
        ),
    ]
