# Generated by Django 5.2.9 on 2025-12-27 23:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_add_medical_record_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.appointment'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='chief_complaint',
            field=models.TextField(blank=True, db_column='chief_complaint', null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='examination_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='radiology_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='staff',
            field=models.ForeignKey(blank=True, db_column='staff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
