# Generated by Django 5.2.9 on 2025-12-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_add_missing_medical_record_fields'),
    ]

    operations = [        migrations.RunSQL(
            "UPDATE medical_records SET staff = created_by WHERE staff IS NULL AND created_by IS NOT NULL;",
            reverse_sql="UPDATE medical_records SET staff = NULL WHERE staff = created_by;",
        ),
        migrations.RunSQL(
            "UPDATE medical_records SET staff = '38124daa-1b1a-4c9e-beb9-aaccc34b8588' WHERE staff IS NULL;",
            reverse_sql="UPDATE medical_records SET staff = NULL WHERE staff = '38124daa-1b1a-4c9e-beb9-aaccc34b8588' AND created_by IS NULL;",
        ),    ]
