# Generated by Django 5.2.9 on 2025-12-27 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_populate_medical_record_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='staff',
            field=models.ForeignKey(db_column='staff', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='staff.staff'),
        ),
    ]
