# Generated by Django 5.2.9 on 2025-12-27 23:40

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_make_medical_record_staff_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, help_text='Actual date/time of appointment session, can differ from scheduled start_time.', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 0, 40, 3, 108910, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
