# Generated by Django 5.2.9 on 2025-12-27 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_appointment_appointment_date_and_more'),
        ('staff', '0017_appointment_appointment_date_and_more'),
    ]

    operations = [
    ]
