# Generated by Django 5.2.9 on 2025-12-28 00:01

import datetime
import django.db.models.deletion
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_merge_20251228_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_records', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 1, 1, 48, 158489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateField(default=staff.models.default_record_date),
        ),
    ]
