# Generated by Django 5.2.9 on 2025-12-28 01:46

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_medicalrecord_created_by_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 2, 46, 47, 509252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('allergy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen_name', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('reaction', models.TextField(blank=True, null=True)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='staff.patient')),
            ],
            options={
                'db_table': 'allergies',
                'ordering': ['allergen_name'],
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('condition_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('managed', 'Managed'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_conditions', to='staff.patient')),
            ],
            options={
                'db_table': 'chronic_conditions',
                'ordering': ['-diagnosed_date', 'condition_name'],
            },
        ),
        migrations.CreateModel(
            name='PastSurgery',
            fields=[
                ('surgery_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=300)),
                ('surgery_date', models.DateField()),
                ('surgeon', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('complications', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_surgeries', to='staff.patient')),
            ],
            options={
                'db_table': 'past_surgeries',
                'ordering': ['-surgery_date'],
            },
        ),
    ]
