# Generated by Django 5.2.9 on 2025-12-28 01:55

import datetime
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_alter_appointment_end_time_allergy_chroniccondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergy_id',
            field=models.UUIDField(default=staff.models.UUIDGenerateV4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 2, 55, 35, 930731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chroniccondition',
            name='condition_id',
            field=models.UUIDField(default=staff.models.UUIDGenerateV4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pastsurgery',
            name='surgery_id',
            field=models.UUIDField(default=staff.models.UUIDGenerateV4, editable=False, primary_key=True, serialize=False),
        ),
    ]
