# Generated by Django 5.2.9 on 2025-12-28 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_update_uuid_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 28, 3, 3, 36, 858512, tzinfo=datetime.timezone.utc)),
        ),
    ]
